# Generated by Django 4.2.3 on 2023-07-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_alter_ingredient_name'),
        ('recipes', '0002_alter_recipe_options_recipe_cooking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='ingredients.ingredient', verbose_name='Ingredients'),
        ),
    ]
