# Generated by Django 4.2.3 on 2023-07-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_ingredientamount_ingredient_and_recipe_in_ingredientamount_is_unique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
    ]
